fix: Convert french_accounting XML files from ISO-8859-1 to UTF-8
All XML files in french_accounting were encoded as ISO-8859-1 which caused
lxml to fail when parsing them:
  OSError: Error reading file 'security.xml': Invalid bytes in character encoding

Converted all XML files to UTF-8:
- security/security.xml
- views/fec_export_views.xml
- views/menu_views.xml
- views/tva_declaration_views.xml
- demo/demo_data.xml

Fixes: XML parsing error preventing module from loading